[book]
authors = ["Max Thomson"]
language = "en"
multilingual = false
src = "src"
title = "Learn JS"

[output.html.playground]
editable = true

[output.html]
additional-js = [
  "mode-javascript.js",
  "editor.js",
]
